### ISSUE TITLE
Bump remark-github to 7.0.3 (mostly to support project names with underscores)

### ISSUE THREAD

**Issue by 4cm4k1** [niftylettuce/remark-preset-github#3]
Hello!

I worked with @wooorm on the project name underscore issue in the 7.0.3 release of `remark-github`: https://github.com/remarkjs/remark-github/tree/7.0.3 Could you bump the version in `package.json` and ship a release? Otherwise, users with project names with underscores will encounter the same issue shown here: https://github.com/remarkjs/remark-github/pull/11

Thanks!

**Comment by niftylettuce** [comment]
remark-preset-github v0.0.8 is now available in npm

`npm install -d remark-preset-github@latest` or `yarn add -d remark-preset-github@latest`
